//<auto-generated />

namespace Windows.Win32
{
    using win32 = global::Windows.Win32;

    static partial class FriendlyOverloadExtensions
    {
        public static void GetAt<T>(this win32.UI.Shell.Common.IObjectArray @this, uint uiIndex, out T ppv)
        {
            @this.GetAt(uiIndex, typeof(T).GUID, out var temp);
            ppv = (T)temp;
        }
    }
}
